//===========================================================
// HexaChipsers RV32IMAFB — RTL Trace Logger Testbench
//-----------------------------------------------------------
// Extends tb_integration with instruction-level trace logging
// for each retired instruction. Output format compatible with
// trace_compare.py for golden model comparison.
//
// Trace format (per line):
//   PC_HEX  INSTR_HEX  [xN DATA_HEX | fN DATA_HEX]
//   90000000 00000097 x01 90000000
//===========================================================

`timescale 1ns / 1ps

module tb_trace_logger;

    //-----------------------------
    // Parameters
    //-----------------------------
    parameter CLK_PERIOD     = 20;       // 50 MHz
    parameter TIMEOUT_CYCLES = 10000000;
    parameter MEM_INIT_FILE  = "test_mem.v";
    parameter TRACE_FILE     = "rtl_trace.txt";

    //-----------------------------
    // Signals (same as tb_integration)
    //-----------------------------
    reg         clk;
    reg         reset_n;
    wire        uart_txd;
    reg         uart_rxd;
    reg         jtag_tck, jtag_tms, jtag_tdi;
    wire        jtag_tdo;
    reg  [31:0] gpio2_in;

    //-----------------------------
    // Clock
    //-----------------------------
    initial clk = 0;
    always #(CLK_PERIOD / 2) clk = ~clk;

    //-----------------------------
    // DUT Instantiation
    // Adapt port names to match actual CHIP_TOP_WRAP
    //-----------------------------
    /*
    CHIP_TOP_WRAP u_dut (
        .CLK50          (clk),
        .RESETn         (reset_n),
        .UART_TXD       (uart_txd),
        .UART_RXD       (uart_rxd),
        .JTAG_TCK       (jtag_tck),
        .JTAG_TMS       (jtag_tms),
        .JTAG_TDI       (jtag_tdi),
        .JTAG_TDO       (jtag_tdo),
        .GPIO2          (gpio2_in)
    );
    */

    //-----------------------------
    // Trace Logger
    //-----------------------------
    integer trace_fd;
    integer instr_count;

    initial begin
        trace_fd = $fopen(TRACE_FILE, "w");
        if (trace_fd == 0) begin
            $display("ERROR: Cannot open %s", TRACE_FILE);
            $finish;
        end
        $fwrite(trace_fd, "# HexaChipsers RV32IMAFB RTL Trace\n");
        $fwrite(trace_fd, "# Format: PC INSTR [xN DATA | fN DATA]\n");
        $fwrite(trace_fd, "# Generated by tb_trace_logger.sv\n");
        instr_count = 0;
    end

    // Instruction retirement detection
    // NOTE: These signal paths must be adapted to actual DUT hierarchy
    // The paths below are examples based on the module structure:
    //
    //   u_dut.u_chip_top.u_cpu_top.PIPE_WB_ENABLE
    //   u_dut.u_chip_top.u_cpu_top.WB_PC
    //   u_dut.u_chip_top.u_cpu_top.WB_INSTR
    //   u_dut.u_chip_top.u_cpu_top.EX_ALU_DST1
    //   u_dut.u_chip_top.u_cpu_top.regfile.mem[rd]
    //
    // Since we don't have the exact hierarchy, this uses placeholder signals.
    // When you have the actual DUT, uncomment and fix the paths.

    /*
    wire        wb_valid = u_dut.u_chip_top.u_hexacore.u_cpu_top.PIPE_WB_ENABLE;
    wire [31:0] wb_pc    = u_dut.u_chip_top.u_hexacore.u_cpu_top.pipe_wb_pc;
    wire [31:0] wb_instr = u_dut.u_chip_top.u_hexacore.u_cpu_top.pipe_wb_code;
    wire [4:0]  wb_rd    = u_dut.u_chip_top.u_hexacore.u_cpu_top.pipe_wb_dst1[4:0];
    wire        wb_rd_en = u_dut.u_chip_top.u_hexacore.u_cpu_top.pipe_wb_dst1_en;
    wire [31:0] wb_rd_data = u_dut.u_chip_top.u_hexacore.u_cpu_top.pipe_wb_dst1_data;

    always @(posedge clk) begin
        if (reset_n && wb_valid) begin
            instr_count <= instr_count + 1;

            if (wb_rd_en && wb_rd != 5'd0) begin
                // GPR writeback
                $fwrite(trace_fd, "%08h %08h x%02d %08h\n",
                        wb_pc, wb_instr, wb_rd, wb_rd_data);
            end else begin
                // No writeback
                $fwrite(trace_fd, "%08h %08h\n", wb_pc, wb_instr);
            end

            // Flush every 1000 instructions
            if (instr_count % 1000 == 0) begin
                $fflush(trace_fd);
                $display("  [TRACE] %0d instructions logged", instr_count);
            end
        end
    end
    */

    //-----------------------------
    // Timeout & Stop
    //-----------------------------
    integer cycle_count;
    initial cycle_count = 0;

    always @(posedge clk) begin
        cycle_count <= cycle_count + 1;
        if (cycle_count >= TIMEOUT_CYCLES) begin
            $display("\n[TIMEOUT] %0d cycles, %0d instructions traced",
                     TIMEOUT_CYCLES, instr_count);
            $fflush(trace_fd);
            $fclose(trace_fd);
            $finish;
        end
    end

    //-----------------------------
    // Reset
    //-----------------------------
    initial begin
        reset_n  = 0;
        uart_rxd = 1;
        jtag_tck = 0;
        jtag_tms = 1;
        jtag_tdi = 0;
        gpio2_in = 0;

        repeat (100) @(posedge clk);
        reset_n = 1;

        $display("===========================================");
        $display(" HexaChipsers Trace Logger Started");
        $display(" Output: %s", TRACE_FILE);
        $display("===========================================");
    end

    final begin
        $fflush(trace_fd);
        $fclose(trace_fd);
        $display(" Total instructions traced: %0d", instr_count);
    end

endmodule
